package nl.novi.backend_eindopdracht.model.course.enums;

public enum CourseType {
    BHV_BASIS_DAGDEEL_LEH,
    BHV_BASIS_DAGDEEL_BRAND_EN_ONTRUIMEN,
    BHV_BASIS_DAG_LEH,
    BHV_BASIS_DAG_BRAND_EN_ONTRUIMEN,
    BHV_HERHALING_DAG,
    BHV_HERHALING_DAGDEEL,
    BHV_PLOEGLEIDER_BASIS,
    BHV_PLOEGLEIDER_HERHALING,
    LEH_DAGDEEL,
    BRAND_EN_ONTRUIMEN,
    LEH,
    BRAND,
    ONTRUIMING_FASE0,
    ONTRUIMING_FASE1,
    ONTRUIMING_FASE2,
    ONTRUIMING_FASE3,
    ONTRUIMING_FASE4,
    REANIMATIE_VOLWASSENE_MET_AED,
    REANIMATIE_KIND_EN_BABY_MET_AED
}